export const STATES = {
  DECLARE_CHARGE: "DECLARE_CHARGE",
  CHECK_RANGE: "CHECK_RANGE",
  MOVE_CHARGERS: "MOVE_CHARGERS",
  COMBAT_PHASE_START: "COMBAT_PHASE_START",
  ATTACKER_STRIKES: "ATTACKER_STRIKES",
  DEFENDER_STRIKES: "DEFENDER_STRIKES",
  COMBAT_RESOLUTION: "COMBAT_RESOLUTION",
  BREAK_TEST: "BREAK_TEST",
  POST_COMBAT: "POST_COMBAT",
};
